# Generated by Django 3.2.5 on 2021-08-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('emid', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=30)),
                ('esalary', models.FloatField()),
                ('eaddress', models.CharField(max_length=30)),
            ],
        ),
    ]
